/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jossalgon' at '11/01/17 23:41' with Gradle 2.10
 *
 * @author jossalgon, @date 11/01/17 23:41
 */
public class Library {
    public static void main( String[] args )
    {
        System.out.println( "Hola Mundo!" );
    }

    public boolean someLibraryMethod() {
        return true;
    }
}

